# Generated by Django 5.1.1 on 2024-09-28 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="rating",
            new_name="voting",
        ),
    ]
