# Generated by Django 5.1.1 on 2024-09-29 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_customuser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
